# Generated by Django 2.1.2 on 2018-10-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181002_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='StudentUser',
        ),
    ]
