# Generated by Django 2.1.2 on 2018-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181002_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='alumni',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(default='emailname@provider.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
