# Generated by Django 2.1.2 on 2018-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181002_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
