# Generated by Django 2.1.2 on 2018-10-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['grade', 'section'], 'verbose_name': 'Student info', 'verbose_name_plural': 'Student info'},
        ),
    ]
