# Generated by Django 2.1.2 on 2018-10-02 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('admission_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('house', models.CharField(choices=[('C', 'Challengers'), ('P', 'Pioneers'), ('E', 'Explorers'), ('V', 'Voyagers')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.StudentInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
